package com.judian.goule.store.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.judian.goule.store.db.NewsBean;
import com.judian.goule.store.db.RoomBean;

import com.judian.goule.store.greendao.NewsBeanDao;
import com.judian.goule.store.greendao.RoomBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig newsBeanDaoConfig;
    private final DaoConfig roomBeanDaoConfig;

    private final NewsBeanDao newsBeanDao;
    private final RoomBeanDao roomBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        newsBeanDaoConfig = daoConfigMap.get(NewsBeanDao.class).clone();
        newsBeanDaoConfig.initIdentityScope(type);

        roomBeanDaoConfig = daoConfigMap.get(RoomBeanDao.class).clone();
        roomBeanDaoConfig.initIdentityScope(type);

        newsBeanDao = new NewsBeanDao(newsBeanDaoConfig, this);
        roomBeanDao = new RoomBeanDao(roomBeanDaoConfig, this);

        registerDao(NewsBean.class, newsBeanDao);
        registerDao(RoomBean.class, roomBeanDao);
    }
    
    public void clear() {
        newsBeanDaoConfig.clearIdentityScope();
        roomBeanDaoConfig.clearIdentityScope();
    }

    public NewsBeanDao getNewsBeanDao() {
        return newsBeanDao;
    }

    public RoomBeanDao getRoomBeanDao() {
        return roomBeanDao;
    }

}
